[workspace]
members = ["cli", "glop", "lp_data"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/mgreenbe/gloprs"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[profile.release]
codegen-units = 1
lto = "thin"

[profile.bench]
inherits = "release"
debug = "line-tables-only"

