[package]
name = "gloprs-glop"
description = "A Rust port of the GLOP linear-programming solver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lp_data = { package = "gloprs-lp-data", path = "../lp_data" }
rand = "0.9.2"

[lib]
name = "glop"

[lints]
workspace = true

[[bench]]
name = "basis_kernels"
harness = false
